services:
  e2e:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - './specs:/usr/src/app/specs'
    depends_on:
      - reservations
      - auth
      - payment
      - notifications
      - mongo
  reservations:
    build:
      context: .
      dockerfile: ../apps/reservations/Dockerfile
      target: development
    command: pnpm run start:dev reservations
    env_file:
      - ../apps/reservations/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
  auth:
    build:
      context: .
      dockerfile: ../apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    env_file:
      - ../apps/auth/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
  payment:
    build:
      context: .
      dockerfile: ../apps/payment/Dockerfile
      target: development
    command: pnpm run start:dev payment
    env_file:
      - ../apps/payment/.env
    volumes:
      - .:/usr/src/app
  notifications:
    build:
      context: .
      dockerfile: ../apps/notifications/Dockerfile
      target: development
    command: pnpm run start:dev notifications
    env_file:
      - ../apps/notifications/.env
    volumes:
      - .:/usr/src/app
  mongo:
    image: mongo
